ljms_frontend:
    resource: "@LjmsGeneralBundle/Resources/config/routing.yml"
    prefix:   /
divisions:
    resource: "@LjmsGeneralBundle/Controller/Admin/DivisionsController.php"
    type:     annotation
teams:
    resource: "@LjmsGeneralBundle/Controller/Admin/TeamsController.php"
    type:     annotation