ljms_frontend:
    resource: "@LjmsGeneralBundle/Resources/config/routing.yml"
    prefix:   /
post:
    resource: "@LjmsGeneralBundle/Controller/Admin/DivisionsController.php"
    type:     annotation