security:
    encoders:
        Ljms\GeneralBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_DIRECTOR:       ROLE_USER
        ROLE_ADMIN:       ROLE_DIRECTOR
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: LjmsGeneralBundle:User }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_firewall:
            pattern:   ^/login$
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path: /admin
                check_path: login_check
                always_use_default_target_path: true
                default_target_path: /admin/games
            logout:
                path:   /logout
                target: /
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/admin/games, roles: [ROLE_DIRECTOR, ROLE_COACH] }
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
