ljms_general_homepage:
    pattern:  /
    defaults: { _controller: LjmsGeneralBundle:Front:index }
ljms_general_about:
    pattern:  /about
    defaults: { _controller: LjmsGeneralBundle:Front:about }
admin:
    pattern:  /admin
    defaults: { _controller: LjmsGeneralBundle:Auth:login }
login_check:
    pattern:  /login_check
logout:
    pattern:  /logout