ljms_general_homepage:
    pattern:  /
    defaults: { _controller: LjmsGeneralBundle:Front:index }
ljms_general_about:
    pattern:  /about
    defaults: { _controller: LjmsGeneralBundle:Front:about }
login:
    pattern:  /login
    defaults: { _controller: LjmsGeneralBundle:Auth:index }
login_check:
    pattern:  /login_check
