Ljms\GeneralBundle\Entity\Divisions:
    properties:
        name:
            - NotBlank: ~
        status:
            - NotBlank: ~
        age_to:
            - NotBlank: ~
        age_from:
            - NotBlank: ~
        base_fee:
            - Type:
                type: digit
                message: "Base fee value should be of type digit"
        addon_fee:
            - Type: 
                type: digit
                message: "Addon fee value should be of type digit"
    getters:
        age_check:
            - "True": { message: "Incorrect years interval!" }

Ljms\GeneralBundle\Entity\Teams:
    properties:
        name:
            - NotBlank:
                message: "Name field is required."
        status:
            - NotBlank:
                message: "Status field is required."
        division_id:
            - NotBlank:
                message: "Division field is required."
        league_type_id:
            - NotBlank:
                message: "League field is required."
        is_visitor:
            - NotBlank:
                message: "Is field is required."

Ljms\GeneralBundle\Entity\User:
    properties:
        username:
            - NotBlank:
                message: "First Name field is required."
        last_name:
            - NotBlank: 
                message: "Last Name field is required."
        address:
            - NotBlank:
                message: "Adress field is required."
        zipcode:
            - NotBlank:
                message: "Zipcode field is required."
            - Type:
                type: digit
                message: "Zipcode fee value should be of type digit"
        city:
            - NotBlank:
                message: "City field is required."
        password:
            - NotBlank:
                message: "Password field is required."
        home_phone:
            - NotBlank:
                message: "Home Phone field is required."
            - Regex: 
                pattern: "/^((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,10}$/"
                message: "Incorrect Home Phone."
        cell_phone:
            - Regex: 
                pattern: "/^((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,10}$/"
                message: "Incorrect Cell Phone."
        alt_phone:
            - Regex: 
                pattern: "/^((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,10}$/"
                message: "Incorrect Alternative Phone."
        alt_phone_2:
            - Regex: 
                pattern: "/^((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,10}$/"
                message: "Incorrect Alt Phone."
        alt_email:
            - Email:
                message: 'The email "{{ value }}" is not a valid email'
        states_id:
            - NotBlank:
                message: "State ID vfield is required."
        email:
            - NotBlank:
                message: "Email field is required."
            - Email:
                message: 'The email "{{ value }}" is not a valid email'