Ljms\GeneralBundle\Entity\Divisions:
    properties:
        name:
            - NotBlank: ~
        status:
            - NotBlank: ~
        age_to:
            - NotBlank: ~
        age_from:
            - NotBlank: ~
        base_fee:
            - Type:
                type: digit
                message: "Base fee value should be of type digit"
        addon_fee:
            - Type: 
                type: digit
                message: "Addon fee value should be of type digit"
    getters:
        age_check:
            - "True": { message: "Incorrect years interval!" }