parameters:
#    ljms_frontend.example.class: Ljms\FrontendBundle\Example

services:
#    ljms_frontend.example:
#        class: %ljms_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
